services:
  traefik:
    image: "traefik:2.10"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websec.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websec"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.email=badia.orive@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      ces2-demo:
        aliases:
          - ces2demo.community-exchange.org
          - accounting.ces2demo.community-exchange.org
          - notifications.ces2demo.community-exchange.org
          - integralces.ces2demo.community-exchange.org
      ces2-prod:
        aliases:
          - app.ces.community
          - accounting.app.ces.community
          - notifications.app.ces.community
          - integralces.app.ces.community
    

volumes:
  letsencrypt:

networks:
  ces2-demo:
    name: ces2demo.community-exchange.org
  ces2-prod:
    name: app.ces.community
